-- Contact messages storage for web-official contact form.
-- Safe to re-run.

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null,
  message text not null,
  source text not null default 'website',
  ip_address text,
  user_agent text,
  status text not null default 'new',
  created_at timestamptz not null default now(),
  created_at_ms bigint not null default (extract(epoch from now()) * 1000)::bigint
);

create index if not exists contact_messages_created_at_ms_idx on public.contact_messages (created_at_ms desc);
create index if not exists contact_messages_status_idx on public.contact_messages (status);

alter table public.contact_messages enable row level security;

-- No public policies by design:
-- - anon/authenticated cannot read or write this table.
-- - service role (used by Edge Function) can insert.

revoke all on table public.contact_messages from anon, authenticated;
